# Generated by Django 4.2.6 on 2023-11-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_categary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categary',
            new_name='Category',
        ),
    ]
